### ISSUE TITLE
RuntimeError: cuda runtime error (11) : invalid argument at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp:663

### ISSUE THREAD

**Issue by Haidong-Kang** [MCG-NJU/MOC-Detector#22]
RuntimeError: cuda runtime error (11) : invalid argument at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp:663 
how to solve it?

**Comment by ArchiZX** [comment]
Maybe you can refer this https://discuss.pytorch.org/t/cuda-runtime-error-11/30080.

**Comment by Haidong-Kang** [comment]
> Maybe you can refer this https://discuss.pytorch.org/t/cuda-runtime-error-11/30080.

Thanks, I have solved this problem.

**Comment by easquelcannotcode** [comment]
> > Maybe you can refer this https://discuss.pytorch.org/t/cuda-runtime-error-11/30080.
> 
> Thanks, I have solved this problem.

Hello, I came across the same problem as you. Could you please share your solutions?
